<?php
$ideapark_customize_mods_ver = "293595b7a06a63ca95549e05e5498f76";
global $ideapark_customize;
$ideapark_customize = [
"0" => [
"section" => "title_tagline",
"refresh" => "#header .logo-wrap",
"refresh_wrapper" => true,
"refresh_id" => "header_logo",
"controls" => [
"logo" => [
"label" => "Logo",
"class" => "WP_Customize_Image_Control",
"sanitize_callback" => "sanitize_text_field",
"priority" => 50,
],
"logo_zoom" => [
"label" => "Logo zoom (Desktop)",
"default" => 1,
"type" => "slider",
"sanitize_callback" => "ideapark_sanitize_float",
"class" => "WP_Customize_Range_Control",
"min" => 0.2,
"max" => 2,
"step" => 0.1,
"priority" => 51,
"refresh" => false,
"refresh_css" => true,
],
"logo_zoom_mobile" => [
"label" => "Logo zoom (Tablet & Mobile)",
"default" => 1,
"type" => "slider",
"sanitize_callback" => "ideapark_sanitize_float",
"class" => "WP_Customize_Range_Control",
"min" => 0.2,
"max" => 2,
"step" => 0.1,
"priority" => 52,
"refresh" => false,
"refresh_css" => true,
],
],
],
"1" => [
"section" => "background_image",
"controls" => [
"hide_inner_background" => [
"label" => "Hide background on inner pages",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
],
],
"2" => [
"title" => "General Theme Settings",
"priority" => 5,
"controls" => [
"home_boxed" => [
"label" => "Layout",
"default" => "fullscreen",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"fullscreen" => "Fullscreen",
"boxed" => "Boxed",
"boxed-white" => "Boxed with White Background",
],
],
"search_type" => [
"label" => "Search type",
"default" => "search-type-2",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"search-type-1" => "Fullscreen (ajax)",
"search-type-2" => "Popup (ajax)",
"search-type-3" => "Popup (without ajax)",
],
],
"ajax_search_limit" => [
"label" => "Number of products in the live search",
"default" => 8,
"min" => 1,
"step" => 1,
"class" => "WP_Customize_Number_Control",
"type" => "number",
"sanitize_callback" => "absint",
"dependency" => [
"search_type" => [
"0" => "search-type-1",
"1" => "search-type-2",
],
],
],
"search_products_only" => [
"label" => "Search products only",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"search_type" => [
"0" => "search-type-1",
"1" => "search-type-2",
],
],
],
"search_by_sku" => [
"label" => "Search by SKU",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"search_type" => [
"0" => "search-type-1",
"1" => "search-type-2",
],
],
],
"search_by_category" => [
"label" => "Search by Category name",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"search_by_tag" => [
"label" => "Search by Tag name",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"search_by_brand_info" => [
"html" => "<a href=\"#\" class=\"ideapark-control-focus\" data-control=\"search_by_brand\"> Search by Brand name </a>",
"class" => "WP_Customize_HTML_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"product_brand_attribute" => [
"0" => "not_empty",
],
],
],
"arrows_type" => [
"label" => "Arrows Prev & Next",
"default" => "normal",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"normal" => "Normal",
"minimal" => "Minimal",
],
],
"disable_block_editor" => [
"label" => "Disable widget block editor",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"sticky_sidebar" => [
"label" => "Sticky sidebar",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"to_top_button" => [
"label" => "To Top Button Enable",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"to_top_button_color" => [
"label" => "To Top Button color",
"description" => "Default color if empty",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "",
"dependency" => [
"to_top_button" => [
"0" => "not_empty",
],
],
],
],
],
"3" => [
"title" => "Header / Menu Settings",
"description" => "This is a settings section to change header options and upload logo.",
"priority" => 90,
"controls" => [
"header_settings_info" => [
"label" => "Header Settings",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"header_type" => [
"label" => "Header type",
"default" => "header-type-1",
"sanitize_callback" => "sanitize_text_field",
"type" => "image-radio",
"class" => "WP_Customize_Image_Radio_Control",
"is_option" => true,
"choices" => [
"header-type-1" => "https://katkotna.com/wp-content/themes/kidz/img/header-1.png",
"header-type-2" => "https://katkotna.com/wp-content/themes/kidz/img/header-2.png",
],
],
"icon_auth" => [
"label" => "Show Login / My Account icon before cart icon",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"refresh" => true,
],
"icon_search" => [
"label" => "Show Search button",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"refresh" => true,
],
"icon_cart" => [
"label" => "Show Cart button",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"refresh" => true,
],
"wishlist_enabled" => [
"label" => "Show Wishlist button",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"refresh" => true,
"dependency" => [
"wishlist_page" => [
"0" => "not_empty",
],
],
],
"wishlist_is_disabled" => [
"label" => "Wishlist button is not shown because Wishlist Page is not set <a href=\"#\" class=\"ideapark-control-focus\" data-control=\"wishlist_page\">here</a>",
"class" => "WP_Customize_Warning_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"wishlist_page" => [
"0" => 0,
"1" => "",
],
],
],
"menu_settings_info" => [
"label" => "Main Menu Settings",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"mega_menu" => [
"label" => "Main menu type",
"default" => true,
"type" => "radio",
"choices" => [
"1" => "Mega Menu",
"0" => "Product category menu",
],
"sanitize_callback" => "ideapark_sanitize_checkbox",
"refresh" => ".main-menu-container",
"refresh_wrapper" => true,
"refresh_id" => "main_menu",
"refresh_callback" => "ideapark_mega_menu_init",
],
"main_menu_view" => [
"label" => "Main menu view",
"default" => "main-menu-icons",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"main-menu-icons" => "Icons with text",
"main-menu-text-only" => "Only text",
],
"refresh" => ".main-menu-container",
"refresh_wrapper" => true,
"refresh_id" => "main_menu",
"refresh_callback" => "ideapark_mega_menu_init",
],
"main_menu_width" => [
"label" => "Menu item width",
"description" => "Only for center logo layout with menu icons",
"default" => 105,
"type" => "slider",
"sanitize_callback" => "ideapark_sanitize_abs_int",
"class" => "WP_Customize_Range_Control",
"min" => 65,
"max" => 170,
"step" => 1,
"refresh" => false,
"refresh_css" => ".main-menu-container",
"refresh_callback" => "ideapark_mega_menu_init",
],
"main_menu_font_size" => [
"label" => "Menu item font-size",
"default" => 12,
"type" => "ideapark_sanitize_abs_int",
"sanitize_callback" => "sanitize_text_field",
"class" => "WP_Customize_Range_Control",
"min" => 10,
"max" => 14,
"step" => 1,
"refresh" => false,
"refresh_css" => ".main-menu-container",
"refresh_callback" => "ideapark_mega_menu_init",
],
"main_menu_responsive" => [
"label" => "Responsive menu item width",
"description" => "Fixed menu item width by default",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"refresh" => true,
],
"top_menu_settings_info" => [
"label" => "Top Menu Settings",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"top_menu" => [
"label" => "Enable top menu",
"refresh" => "#home-top-menu",
"refresh_wrapper" => true,
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"top_menu_color" => [
"label" => "Text color",
"description" => "Default color if empty",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "",
"refresh" => "#home-top-menu",
"refresh_wrapper" => true,
"refresh_id" => "top_menu",
],
"top_menu_background_color" => [
"label" => "Top menu background color",
"description" => "Transparent if empty",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"refresh" => "#home-top-menu",
"refresh_wrapper" => true,
"refresh_id" => "top_menu",
"default" => "",
],
"top_menu_text" => [
"label" => "Top menu text",
"description" => "You can put contact phones or working time here",
"type" => "text_editor",
"default" => "",
"sanitize_callback" => "wp_kses_post",
"refresh" => "#home-top-menu",
"refresh_wrapper" => true,
"refresh_id" => "top_menu",
"class" => "WP_Customize_Text_Editor_Control",
],
"top_menu_text_phone_clickable" => [
"label" => "Clickable phone number in top menu text",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"top_menu_auth" => [
"label" => "Show button Login / My Account ",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"refresh" => true,
],
"sticky_menu_settings_info" => [
"label" => "Sticky Menu Settings",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"sticky_menu" => [
"label" => "Sticky menu",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"sticky_type" => [
"label" => "Sticky menu view",
"default" => "sticky-type-1",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"sticky-type-1" => "Icons only",
"sticky-type-2" => "Text only",
],
],
],
],
"4" => [
"title" => "Footer Settings",
"refresh" => "#footer",
"refresh_wrapper" => true,
"refresh_id" => "footer",
"priority" => 105,
"controls" => [
"footer_layout" => [
"label" => "Footer layout",
"default" => "default",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"refresh" => true,
"choices" => [
"default" => "Default (Contact block + 3 Widgets)",
"widgets" => "4 Widgets",
"minimal" => "Minimal (Copyright and Social icons)",
],
],
"logo_footer" => [
"label" => "Retina Logo (optional)",
"description" => "Retina Ready Image logo. It should has width 220px (for landscape style logo) or height 220px (for portrait style logo)",
"class" => "WP_Customize_Image_Control",
"sanitize_callback" => "sanitize_text_field",
"refresh" => "#footer .footer-logo",
"refresh_wrapper" => true,
"dependency" => [
"footer_layout" => [
"0" => "default",
],
],
],
"footer_contacts" => [
"label" => "Contacts",
"description" => "Only in Widgets Footer Design",
"type" => "text_editor",
"default" => "",
"sanitize_callback" => "wp_kses_post",
"refresh" => "#footer .contacts",
"refresh_wrapper" => false,
"class" => "WP_Customize_Text_Editor_Control",
"dependency" => [
"footer_layout" => [
"0" => "default",
],
],
],
"footer_copyright" => [
"label" => "Copyright",
"description" => "Also you can paste shortcode, generated with any  plugin",
"type" => "text_editor",
"default" => "&copy; Copyright 2022, Kidz WordPress Theme",
"sanitize_callback" => "wp_kses_post",
"class" => "WP_Customize_Text_Editor_Control",
"refresh" => "#footer .copyright",
"refresh_wrapper" => false,
],
"footer_text_color" => [
"label" => "Text color",
"description" => "Default color if empty",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "",
"refresh" => true,
],
"footer_background_color" => [
"label" => "Background color",
"description" => "Default color if empty",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "",
"refresh" => true,
],
],
],
"5" => [
"title" => "Social Media Links",
"description" => "Add the full url of your social media page e.g http://twitter.com/yoursite",
"refresh" => ".soc",
"refresh_wrapper" => true,
"refresh_id" => "soc",
"priority" => 130,
"controls" => [
"soc_background_color" => [
"label" => "Background color",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "#404E65",
"refresh" => true,
],
"soc_color" => [
"label" => "Icon color",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "#FFFFFF",
"refresh" => true,
],
"facebook" => [
"label" => "Facebook url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"instagram" => [
"label" => "Instagram url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"vk" => [
"label" => "VK url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"ok" => [
"label" => "OK url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"telegram" => [
"label" => "Telegram url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"whatsapp" => [
"label" => "Whatsapp url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"twitter" => [
"label" => "X (Twitter) url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"youtube" => [
"label" => "YouTube url",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"vimeo" => [
"label" => "Vimeo url",
"type" => "text",
"sanitize_callback" => "sanitize_text_field",
],
"snapchat" => [
"label" => "Snapchat url",
"type" => "text",
"sanitize_callback" => "sanitize_text_field",
],
"tiktok" => [
"label" => "TikTok url",
"type" => "text",
"sanitize_callback" => "sanitize_text_field",
],
"linkedin" => [
"label" => "LinkedIn url",
"type" => "text",
"sanitize_callback" => "sanitize_text_field",
],
"flickr" => [
"label" => "Flickr url",
"type" => "text",
"sanitize_callback" => "sanitize_text_field",
],
"pinterest" => [
"label" => "Pinterest url",
"type" => "text",
"sanitize_callback" => "sanitize_text_field",
],
"tumblr" => [
"label" => "Tumblr url",
"type" => "text",
"sanitize_callback" => "sanitize_text_field",
],
"dribbble" => [
"label" => "Dribbble url",
"type" => "text",
"sanitize_callback" => "sanitize_text_field",
],
"github" => [
"label" => "Github url",
"type" => "text",
"sanitize_callback" => "sanitize_text_field",
],
"custom_soc_info" => [
"label" => "Custom Social Icon",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"custom_soc_icon" => [
"label" => "Icon",
"class" => "WP_Customize_Image_Control",
"sanitize_callback" => "sanitize_text_field",
],
"custom_soc_url" => [
"label" => "Url",
"type" => "text",
"sanitize_callback" => "sanitize_text_field",
],
],
],
"6" => [
"panel" => "front_page_builder",
"title" => "General settings",
"controls" => [
"front_page_builder_enabled" => [
"label" => "Enable Front Page builder",
"description" => "If Front Page Builder is off - native page content will be shown",
"default" => true,
"refresh" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"home_sections" => [
"label" => "Sections order",
"description" => "Drag and drop sections below to set up their order on the Front Page. You can also enable or disable any section.",
"type" => "checklist",
"default" => "slider=1|banner-4=1|product-tabs=1|brands=1|big-banner=0|posts=1|reviews=1|text=1|subscribe=0|html=0|shortcode=0",
"choices" => [
"slider" => "Slider",
"banner-4" => "Banner block (3/4 per row)",
"big-banner" => "Big banner",
"product-tabs" => "Product tabs",
"brands" => "Brands",
"posts" => "Blog Posts",
"reviews" => "Reviews",
"text" => "Home page content",
"html" => "HTML block",
"shortcode" => "Shortcode",
"subscribe" => "Subscribe",
],
"choices_edit" => [
"slider" => "home_slider_is_disabled",
"banner-4" => "home_banner_4_is_disabled",
"big-banner" => "home_banner_big_is_disabled",
"product-tabs" => "home_tab_products_is_disabled",
"brands" => "home_brands_is_disabled",
"posts" => "home_post_is_disabled",
"reviews" => "home_reviews_is_disabled",
"text" => "home_text_is_disabled",
"html" => "home_html_is_disabled",
"shortcode" => "home_shortcode_is_disabled",
"subscribe" => "home_subscribe_is_disabled",
],
"can_add_block" => [
"0" => "product-tabs",
"1" => "html",
"2" => "shortcode",
],
"add_ajax_action" => "ideapark_customizer_add_section",
"delete_ajax_action" => "ideapark_customizer_delete_section",
"sortable" => true,
"class" => "WP_Customize_Checklist_Control",
"sanitize_callback" => "sanitize_text_field",
],
],
],
"7" => [
"section_id" => "slider",
"title" => "Slider",
"panel" => "front_page_builder",
"refresh" => "#home-slider",
"refresh_wrapper" => true,
"refresh_id" => "home-slider",
"refresh_callback" => "ideapark_init_home_slider",
"controls" => [
"home_slider_is_disabled" => [
"label" => "This section is not shown because it is disabled in <a href=\"#\" class=\"ideapark-control-focus\" data-control=\"home_sections\">General settings</a>",
"class" => "WP_Customize_Warning_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"home_sections" => [
"0" => "search!=slider=1",
],
],
],
"home_fullwidth_slider" => [
"label" => "Fullwidth",
"default" => true,
"refresh" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"slider_shortcode" => [
"label" => "Third-party slider shortcode",
"description" => "Enter shortcode, if you want to use a third-party slider instead of the theme slider",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"slider_effect" => [
"label" => "Effect",
"default" => "slide",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"fade" => "Fade",
"slide" => "Slide",
],
],
"slider_items" => [
"label" => "Slider Items",
"default" => 5,
"step" => 1,
"min" => 1,
"class" => "WP_Customize_Number_Control",
"type" => "number",
"sanitize_callback" => "absint",
],
"slider_interval" => [
"label" => "Autoplay interval (ms)",
"description" => "Set to zero if you want to disable autoplay",
"default" => 5000,
"step" => 1,
"min" => 0,
"class" => "WP_Customize_Number_Control",
"type" => "number",
"sanitize_callback" => "absint",
],
"slider_hide_arrows" => [
"label" => "Hide navigation arrows",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"slider_hide_dots" => [
"label" => "Hide navigation dots",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"home_slider_edit" => [
"html" => "You can change the slides <a href=\"https://katkotna.com/wp-admin/edit.php?post_type=slider\">here</a>",
"class" => "WP_Customize_HTML_Control",
"sanitize_callback" => "sanitize_text_field",
],
],
],
"8" => [
"section_id" => "banner-4",
"title" => "Banners (3/4 per row)",
"panel" => "front_page_builder",
"refresh" => "#home-banners",
"refresh_wrapper" => true,
"refresh_id" => "home-banners",
"controls" => [
"home_banner_4_is_disabled" => [
"label" => "This section is not shown because it is disabled in <a href=\"#\" class=\"ideapark-control-focus\" data-control=\"home_sections\">General settings</a>",
"class" => "WP_Customize_Warning_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"home_sections" => [
"0" => "search!=banner-4=1",
],
],
],
"home_banners_4_order" => [
"label" => "Sort order",
"default" => "fixed",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"fixed" => "Fixed",
"random" => "Random",
],
],
"home_banners_edit" => [
"html" => "You can change the banners <a href=\"https://katkotna.com/wp-admin/edit.php?post_type=banner\">here</a>",
"class" => "WP_Customize_HTML_Control",
"sanitize_callback" => "sanitize_text_field",
],
],
],
"9" => [
"section_id" => "big-banner",
"title" => "Big banner",
"panel" => "front_page_builder",
"refresh" => "#home-big-banner",
"refresh_wrapper" => true,
"refresh_id" => "home-big-banner",
"refresh_pre_callback" => "ideapark_parallax_destroy",
"refresh_callback" => "ideapark_parallax_init",
"controls" => [
"home_banner_big_is_disabled" => [
"label" => "This section is not shown because it is disabled in <a href=\"#\" class=\"ideapark-control-focus\" data-control=\"home_sections\">General settings</a>",
"class" => "WP_Customize_Warning_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"home_sections" => [
"0" => "search!=big-banner=1",
],
],
],
"home_big_banner_header" => [
"label" => "Header",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"home_big_banner_subheader" => [
"label" => "Sub header",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"home_big_banner_button_text" => [
"label" => "Button text",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"home_big_banner_text_align" => [
"label" => "Text align",
"section" => "background_image",
"type" => "select",
"sanitize_callback" => "sanitize_text_field",
"default" => "text-center",
"choices" => [
"text-left" => "Left",
"text-center" => "Center",
"text-right" => "Right",
],
],
"home_big_banner_link" => [
"label" => "Link",
"description" => "If button text empty whole banner areal would be the link",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"home_big_banner_image" => [
"label" => "Image",
"class" => "WP_Customize_Image_Control",
"sanitize_callback" => "sanitize_text_field",
],
"home_big_banner_image_position_x" => [
"label" => "Image position X",
"type" => "select",
"sanitize_callback" => "sanitize_text_field",
"default" => "center",
"choices" => [
"left" => "Left",
"center" => "Center",
"right" => "Right",
],
],
"home_big_banner_image_position_y" => [
"label" => "Image position Y",
"type" => "select",
"sanitize_callback" => "sanitize_text_field",
"default" => "center",
"choices" => [
"top" => "Top",
"center" => "Center",
"bottom" => "Bottom",
],
],
"home_big_banner_image_size" => [
"label" => "Image size",
"type" => "select",
"sanitize_callback" => "sanitize_text_field",
"default" => "auto",
"choices" => [
"auto" => "Original",
"contain" => "Fit to banner area",
"cover" => "Fill banner area",
],
],
"home_big_banner_parallax" => [
"label" => "Parallax",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"home_big_banner_text_color" => [
"label" => "Text color",
"class" => "WP_Customize_Color_Control",
"default" => "#404E65",
"sanitize_callback" => "sanitize_text_field",
],
"home_big_banner_button_color" => [
"label" => "Button color",
"class" => "WP_Customize_Color_Control",
"default" => "#404E65",
"sanitize_callback" => "sanitize_text_field",
],
"home_big_banner_background_color" => [
"label" => "Background color",
"description" => "Leave empty for transparent background",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"home_big_banner_container" => [
"label" => "Boxed view",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
],
],
"10" => [
"section_id" => "product-tabs",
"title" => "Product Tabs",
"panel" => "front_page_builder",
"refresh" => "#home-tabs",
"refresh_wrapper" => true,
"refresh_id" => "home-tabs",
"refresh_callback" => "ideapark_init_home_tabs",
"controls" => [
"home_tab_products_is_disabled" => [
"label" => "This section is not shown because it is disabled in <a href=\"#\" class=\"ideapark-control-focus\" data-control=\"home_sections\">General settings</a>",
"class" => "WP_Customize_Warning_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"home_sections" => [
"0" => "search!=product-tabs=1",
],
],
],
"home_tab_products" => [
"label" => "Products in tab",
"description" => "The number of products in the home tabs.",
"default" => 12,
"step" => 1,
"min" => 1,
"class" => "WP_Customize_Number_Control",
"type" => "number",
"sanitize_callback" => "absint",
],
"home_tab_orderby" => [
"label" => "Order by",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"type" => "select",
"choices" => [
"" => "default",
"date" => "date the product was published",
"id" => "post ID of the product",
"menu_order" => "menu order",
"popularity" => "number of purchases",
"rand" => "random",
"rating" => "average product rating",
"title" => "product title",
],
],
"home_tab_order" => [
"label" => "Order",
"default" => "ASC",
"sanitize_callback" => "sanitize_text_field",
"type" => "select",
"choices" => [
"ASC" => "ASC",
"DESC" => "DESC",
],
"dependency" => [
"home_tab_orderby" => [
"0" => "not_empty",
],
],
],
"home_tab_carousel" => [
"label" => "Carousel",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"home_tab_view_more" => [
"label" => "View more button",
"description" => "For category tabs only",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"home_tab_view_more_item" => [
"label" => "Show view more button as last product",
"description" => "For category tabs with carousel only",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"home_tab_carousel" => [
"0" => 1,
],
],
],
"home_product_order" => [
"label" => "Tab list",
"description" => "Add or delete tab, and then drag and drop tabs below to set up their order. You can also enable or disable any tab",
"type" => "checklist",
"default" => "featured_products=1|sale_products=1|best_selling_products=1|recent_products=1",
"choices" => [
],
"choices_add" => "ideapark_customizer_product_tab_list",
"sortable" => true,
"class" => "WP_Customize_Checklist_Control",
"sanitize_callback" => "sanitize_text_field",
],
"home_tab_shortcode" => [
"label" => "Tab products shortcode",
"description" => "For tab with woocommerce shortcode",
"default" => "",
"type" => "text",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"home_product_order" => [
"0" => "search=shortcode=1",
],
],
],
"home_tab_shortcode_manual" => [
"label" => "<a href=\"https://docs.woocommerce.com/document/woocommerce-shortcodes/\" target=\"_blank\">Shortcodes included with WooCommerce</a>",
"class" => "WP_Customize_Notice_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"home_product_order" => [
"0" => "search=shortcode=1",
],
],
],
"home_tab_shortcode_title" => [
"label" => "Shortcode tab header",
"default" => "Products",
"type" => "text",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"home_product_order" => [
"0" => "search=shortcode=1",
],
],
],
"home_featured_title" => [
"label" => "Featured products tab header",
"default" => "Featured",
"type" => "text",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"home_product_order" => [
"0" => "search=featured_products=1",
],
],
],
"home_sale_title" => [
"label" => "Sale products tab header",
"default" => "On a Sale",
"type" => "text",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"home_product_order" => [
"0" => "search=sale_products=1",
],
],
],
"home_best_selling_title" => [
"label" => "Best-Selling products tab header",
"default" => "Bestsellers",
"type" => "text",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"home_product_order" => [
"0" => "search=best_selling_products=1",
],
],
],
"home_recent_title" => [
"label" => "Recent products tab header",
"default" => "Latest",
"type" => "text",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"home_product_order" => [
"0" => "search=recent_products=1",
],
],
],
"home_tab_background_color" => [
"label" => "Background color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"home_tab_padding_top" => [
"label" => "Add top padding",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"home_tab_padding_bottom" => [
"label" => "Add bottom padding",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
],
],
"11" => [
"section_id" => "brands",
"title" => "Brands",
"panel" => "front_page_builder",
"refresh" => "#home-brand",
"refresh_wrapper" => true,
"refresh_id" => "home-brands",
"refresh_callback" => "ideapark_init_home_brands_carousel",
"controls" => [
"home_brands_is_disabled" => [
"label" => "This section is not shown because it is disabled in <a href=\"#\" class=\"ideapark-control-focus\" data-control=\"home_sections\">General settings</a>",
"class" => "WP_Customize_Warning_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"home_sections" => [
"0" => "search!=brands=1",
],
],
],
"home_brands_interval" => [
"label" => "Autoplay interval (ms)",
"description" => "Set to zero if you want to disable autoplay",
"default" => 0,
"step" => 1,
"min" => 0,
"class" => "WP_Customize_Number_Control",
"type" => "number",
"sanitize_callback" => "absint",
],
"home_brands_background_color" => [
"label" => "Background Color",
"class" => "WP_Customize_Color_Control",
"default" => "#F4F8FF",
"sanitize_callback" => "sanitize_text_field",
],
"home_brands_mobile_dots" => [
"label" => "Show navigation dots on mobile",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"home_brands_edit" => [
"html" => "You can change the brands <a href=\"https://katkotna.com/wp-admin/edit.php?post_type=brand\">here</a>",
"class" => "WP_Customize_HTML_Control",
"sanitize_callback" => "sanitize_text_field",
],
],
],
"12" => [
"section_id" => "posts",
"title" => "Blog Posts",
"panel" => "front_page_builder",
"refresh" => "#home-post",
"refresh_wrapper" => true,
"refresh_id" => "home-posts",
"controls" => [
"home_post_is_disabled" => [
"label" => "This section is not shown because it is disabled in <a href=\"#\" class=\"ideapark-control-focus\" data-control=\"home_sections\">General settings</a>",
"class" => "WP_Customize_Warning_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"home_sections" => [
"0" => "search!=posts=1",
],
],
],
"home_post_title" => [
"label" => "Section Header",
"default" => "Blog Posts",
"type" => "text",
"sanitize_callback" => "sanitize_text_field",
],
"home_post_category" => [
"label" => "Posts Category",
"description" => "Select category if you want the posts from this category to be shown at the bottom of the home page",
"default" => 0,
"class" => "WP_Customize_Category_Control",
"sanitize_callback" => "absint",
],
"home_post_background_color" => [
"label" => "Background Color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"home_post_count" => [
"label" => "Posts in section",
"default" => 4,
"type" => "number",
"sanitize_callback" => "absint",
],
],
],
"13" => [
"section_id" => "reviews",
"title" => "Reviews",
"panel" => "front_page_builder",
"refresh" => "#home-review",
"refresh_wrapper" => true,
"refresh_id" => "home-reviews",
"refresh_callback" => "ideapark_init_home_review",
"controls" => [
"home_reviews_is_disabled" => [
"label" => "This section is not shown because it is disabled in <a href=\"#\" class=\"ideapark-control-focus\" data-control=\"home_sections\">General settings</a>",
"class" => "WP_Customize_Warning_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"home_sections" => [
"0" => "search!=reviews=1",
],
],
],
"home_review_interval" => [
"label" => "Autoplay interval (ms)",
"description" => "Set to zero if you want to disable autoplay",
"default" => 0,
"step" => 1,
"min" => 0,
"class" => "WP_Customize_Number_Control",
"type" => "number",
"sanitize_callback" => "absint",
],
"home_review_background_color" => [
"label" => "Background Color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"home_review_mobile_dots" => [
"label" => "Show navigation dots on mobile",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"home_review_edit" => [
"html" => "You can change the reviews <a href=\"https://katkotna.com/wp-admin/edit.php?post_type=review\">here</a>",
"class" => "WP_Customize_HTML_Control",
"sanitize_callback" => "sanitize_text_field",
],
],
],
"14" => [
"section_id" => "text",
"title" => "Home page content",
"panel" => "front_page_builder",
"refresh" => "#home-text",
"refresh_wrapper" => true,
"refresh_id" => "home-text",
"controls" => [
"home_text_is_disabled" => [
"label" => "This section is not shown because it is disabled in <a href=\"#\" class=\"ideapark-control-focus\" data-control=\"home_sections\">General settings</a>",
"class" => "WP_Customize_Warning_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"home_sections" => [
"0" => "search!=text=1",
],
],
],
"home_text_background_color" => [
"label" => "Background Color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"home_text_hide_header" => [
"label" => "Hide Header",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
],
],
"15" => [
"section_id" => "html",
"title" => "HTML block",
"panel" => "front_page_builder",
"refresh" => "#home-html",
"refresh_wrapper" => true,
"refresh_id" => "home-html",
"refresh_callback" => "ideapark_third_party_reload",
"controls" => [
"home_html_is_disabled" => [
"label" => "This section is not shown because it is disabled in <a href=\"#\" class=\"ideapark-control-focus\" data-control=\"home_sections\">General settings</a>",
"class" => "WP_Customize_Warning_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"home_sections" => [
"0" => "search!=html=1",
],
],
],
"home_html_header" => [
"label" => "Header",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"home_html_content_type" => [
"label" => "Content Source",
"default" => "WYSIWYG",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"WYSIWYG" => "WYSIWYG editor",
"source" => "Source Code (HTML, JavaScript)",
],
],
"home_html_content" => [
"label" => "Content",
"description" => "Also you can paste shortcode, generated with any  plugin (for example, Contacts Form 7)",
"type" => "text_editor",
"default" => "",
"sanitize_callback" => "wp_kses_post",
"class" => "WP_Customize_Text_Editor_Control",
"dependency" => [
"home_html_content_type" => [
"0" => "WYSIWYG",
],
],
],
"home_html_content_source" => [
"label" => "Content",
"description" => "Source Code (Shortcode, HTML, JavaScript)",
"type" => "textarea",
"default" => "",
"sanitize_callback" => "ideapark_sanitize_source_code",
"dependency" => [
"home_html_content_type" => [
"0" => "source",
],
],
],
"home_html_background_color" => [
"label" => "Background Color",
"description" => "Leave empty for transparent background",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"home_html_container" => [
"label" => "Show html inside container",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"home_html_margins" => [
"label" => "Add top and bottom paddings",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
],
],
"16" => [
"section_id" => "shortcode",
"title" => "Shortcode block",
"panel" => "front_page_builder",
"refresh" => "#home-shortcode",
"refresh_id" => "home-shortcode",
"refresh_callback" => "ideapark_third_party_reload",
"refresh_wrapper" => true,
"controls" => [
"home_shortcode_is_disabled" => [
"label" => "This section is not shown because it is disabled in <a href=\"#\" class=\"ideapark-control-focus\" data-control=\"home_sections\">General settings</a>",
"class" => "WP_Customize_Warning_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"home_sections" => [
"0" => "search!=shortcode=1",
],
],
],
"home_shortcode_header" => [
"label" => "Header",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"home_shortcode_content" => [
"label" => "Shortcode",
"description" => "Paste shortcode, generated with any  plugin (for example, Contacts Form 7)",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"home_shortcode_background_color" => [
"label" => "Background Color",
"description" => "Leave empty for transparent background",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"home_shortcode_container" => [
"label" => "Show code inside container",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"home_shortcode_margins" => [
"label" => "Add top and bottom paddings",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
],
],
"17" => [
"section_id" => "subscribe",
"title" => "Subscribe block",
"panel" => "front_page_builder",
"refresh" => "#home-subscribe",
"refresh_id" => "home-subscribe",
"refresh_wrapper" => true,
"controls" => [
"home_subscribe_is_disabled" => [
"label" => "This section is not shown because it is disabled in <a href=\"#\" class=\"ideapark-control-focus\" data-control=\"home_sections\">General settings</a>",
"class" => "WP_Customize_Warning_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"home_sections" => [
"0" => "search!=subscribe=1",
],
],
],
"home_subscribe_header" => [
"label" => "Header",
"type" => "text",
"default" => "Subscribe to Newsletter",
"sanitize_callback" => "sanitize_text_field",
],
"home_subscribe_content" => [
"label" => "Shortcode",
"description" => "Paste subscribe, generated with any subscribe plugin (for example, MailChimp)",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"home_subscribe_background_color" => [
"label" => "Background Color",
"description" => "Leave empty for transparent background",
"class" => "WP_Customize_Color_Control",
"default" => "#EFF7FF",
"sanitize_callback" => "sanitize_text_field",
],
"home_subscribe_container" => [
"label" => "Show code inside container",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"home_subscribe_margins" => [
"label" => "Add top and bottom paddings",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
],
],
"18" => [
"title" => "Fonts",
"priority" => 45,
"controls" => [
"theme_font_0" => [
"label" => "Content font (Google Font)",
"default" => "Open Sans",
"description" => "Default font: Open Sans",
"sanitize_callback" => "ideapark_sanitize_font_choice",
"type" => "select",
"choices" => "ideapark_get_font_choices",
],
"theme_font_1" => [
"label" => "Main Font 1 (Google Font)",
"default" => "Fredoka",
"description" => "Default font: Fredoka",
"sanitize_callback" => "ideapark_sanitize_font_choice",
"type" => "select",
"choices" => "ideapark_get_font_choices",
],
"theme_font_1_weight" => [
"label" => "Font 1 Weight",
"default" => "600",
"description" => "Default: 600",
"sanitize_callback" => "sanitize_text_field",
"type" => "select",
"choices" => [
"100" => "100",
"200" => "200",
"300" => "300",
"400" => "400 (normal)",
"500" => "500",
"600" => "600",
"700" => "700 (bold)",
"800" => "800",
"900" => "900",
],
],
"theme_font_2" => [
"label" => "Main Font 2 (Google Font)",
"default" => "Montserrat",
"description" => "Default font: Montserrat",
"sanitize_callback" => "ideapark_sanitize_font_choice",
"type" => "select",
"choices" => "ideapark_get_font_choices",
],
"theme_font_subsets" => [
"label" => "Main Fonts subset (if available)",
"default" => "latin-ext",
"description" => "Default: Latin Extended",
"sanitize_callback" => "sanitize_text_field",
"type" => "select",
"choices" => "ideapark_get_google_font_subsets",
],
],
],
"19" => [
"title" => "Post/Page Settings",
"priority" => 107,
"section_id" => "post_page",
"controls" => [
"post_hide_featured_image" => [
"label" => "Hide Featured Image",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"post_hide_category" => [
"label" => "Hide Category",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"post_hide_date" => [
"label" => "Hide Date",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"post_hide_share" => [
"label" => "Hide Share Buttons",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"post_hide_tags" => [
"label" => "Hide Tags",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"post_hide_comment" => [
"label" => "Hide Comment Link",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"post_hide_author" => [
"label" => "Hide Author Info",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"post_hide_postnav" => [
"label" => "Hide Post Navigation",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"post_hide_related" => [
"label" => "Hide Related Posts",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"sidebar_info" => [
"label" => "Show sidebar",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"sidebar_blog" => [
"label" => "Blog",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"sidebar_post" => [
"label" => "Post",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"sidebar_page" => [
"label" => "Page",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
],
],
"20" => [
"title" => "Contact Page Settings",
"priority" => 108,
"section_id" => "contact",
"controls" => [
"contact_phones" => [
"label" => "Phones",
"type" => "text_editor",
"default" => "1-800-312-2121",
"sanitize_callback" => "wp_kses_post",
"refresh" => "#contact-block-phones",
"refresh_wrapper" => false,
"class" => "WP_Customize_Text_Editor_Control",
],
"contact_email" => [
"label" => "Email",
"type" => "text_editor",
"default" => "<a href=\"mailto:example@domain.net\">example@domain.net</a>",
"sanitize_callback" => "wp_kses_post",
"refresh" => "#contact-block-email",
"refresh_wrapper" => false,
"class" => "WP_Customize_Text_Editor_Control",
],
"contact_address" => [
"label" => "Address",
"type" => "text_editor",
"default" => "555 California str, Suite 100<br>San Francisco, CA 94107",
"sanitize_callback" => "wp_kses_post",
"refresh" => "#contact-block-address",
"refresh_wrapper" => false,
"class" => "WP_Customize_Text_Editor_Control",
],
"contact_form_shortcode" => [
"label" => "Shortcode with contact form",
"description" => "Paste shortcode, generated with any form plugin (for example, Contacts Form 7). You can also paste any other shortcodes, changing thus the purpose of this section",
"type" => "text",
"default" => "",
"refresh" => "#contact-form",
"transport" => "refresh",
"refresh_wrapper" => false,
"sanitize_callback" => "sanitize_text_field",
],
"contact_map_shortcode" => [
"label" => "Map code",
"description" => "Paste embed html code or shortcode, generated with any map plugin",
"type" => "textarea",
"default" => "",
"refresh" => "#contact-map",
"transport" => "refresh",
"refresh_wrapper" => false,
"sanitize_callback" => "ideapark_sanitize_embed_field",
],
],
],
"21" => [
"title" => "Performance",
"description" => "Use these options to put your theme to a high speed as well as save your server resources!",
"priority" => 130,
"controls" => [
"use_minified_css" => [
"label" => "Use minified CSS",
"description" => "Load all theme css files combined and minified into a single file",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"use_minified_js" => [
"label" => "Use minified JS",
"description" => "Load all theme js files combined and minified into a single file",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"load_jquery_in_footer" => [
"label" => "Load jQuery in footer",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"lazyload" => [
"label" => "Lazy load images",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"google_fonts_display_swap" => [
"label" => "Use parameter display=swap for Google Fonts",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"js_delay" => [
"label" => "Delay JavaScript execution",
"description" => "Improves performance by delaying the execution of JavaScript until user interaction (e.g. scroll, click). ",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
],
],
"22" => [
"section" => "colors",
"controls" => [
"accent_color_custom" => [
"label" => "Accent Color",
"class" => "WP_Customize_Color_Control",
"default" => "#56B0F2",
"sanitize_callback" => "sanitize_text_field",
"refresh" => false,
"refresh_css" => true,
],
"accent_color_2_custom" => [
"label" => "Second Accent Color",
"class" => "WP_Customize_Color_Control",
"default" => "#FF5B4B",
"sanitize_callback" => "sanitize_text_field",
"refresh" => false,
"refresh_css" => true,
],
"base_color_custom" => [
"label" => "Base Color",
"class" => "WP_Customize_Color_Control",
"default" => "#404E65",
"sanitize_callback" => "sanitize_text_field",
"refresh" => false,
"refresh_css" => true,
],
"star_color_custom" => [
"label" => "Star Rating Color",
"description" => "Accent is used if nothing is specified",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"refresh" => false,
"refresh_css" => true,
],
],
],
"23" => [
"panel" => "woocommerce",
"section" => "woocommerce_store_notice",
"controls" => [
"store_notice" => [
"label" => "Store notice placement",
"default" => "top",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"priority" => 50,
"choices" => [
"top" => "At the top of the page",
"bottom" => "At the bottom of the screen (fixed)",
],
"dependency" => [
"woocommerce_demo_store" => [
"0" => "not_empty",
],
],
],
"store_notice_button_hide" => [
"label" => "Hide button",
"priority" => 51,
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"woocommerce_demo_store" => [
"0" => "not_empty",
],
],
],
"store_notice_button_text" => [
"label" => "Custom button text",
"description" => "Default if empty",
"type" => "text",
"priority" => 51,
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"store_notice_button_hide" => [
"0" => "is_empty",
],
"woocommerce_demo_store" => [
"0" => "not_empty",
],
],
],
"store_notice_color" => [
"label" => "Text color ",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "",
"priority" => 52,
"dependency" => [
"woocommerce_demo_store" => [
"0" => "not_empty",
],
],
],
"store_notice_background_color" => [
"label" => "Background color",
"class" => "WP_Customize_Color_Control",
"sanitize_callback" => "sanitize_text_field",
"default" => "",
"priority" => 53,
"dependency" => [
"woocommerce_demo_store" => [
"0" => "not_empty",
],
],
],
],
],
"24" => [
"panel" => "woocommerce",
"title" => "General",
"priority" => 0,
"section_id" => "woocommerce",
"controls" => [
"disable_purchase" => [
"label" => "Disable purchase",
"description" => "Completely disables the ability to order products, turning the site into a showcase of goods.",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"hide_prices" => [
"label" => "Hide prices",
"description" => "Hide prices in the grid and on the product page.",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"hide_uncategorized" => [
"label" => "Hide Uncategorized (default) category",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"hidden_product_category" => [
"label" => "Hide category with products",
"description" => "Products will be available only by direct link",
"default" => 0,
"class" => "WP_Customize_Product_Categories_Control",
"sanitize_callback" => "absint",
],
"hide_variable_price_range" => [
"label" => "Hide price range in the variable product",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"product_breadcrumbs_home" => [
"label" => "Show Home in breadcrumbs",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"product_thumbnail_cart_mobile" => [
"label" => "Show product thumbnails on the Cart page on mobile devices",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
],
],
"25" => [
"panel" => "woocommerce",
"title" => "Product Grid",
"priority" => 2,
"section_id" => "woocommerce_grid",
"controls" => [
"is_shop_configured" => [
"label" => "",
"description" => "",
"type" => "hidden",
"default" => "ideapark_is_shop_configured",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"class" => "WP_Customize_Hidden_Control",
],
"shop_is_not_configured" => [
"label" => "Shop Page is not configured <a href=\"https://katkotna.com/wp-admin/admin.php?page=wc-settings&#038;tab=products\">here</a>",
"class" => "WP_Customize_Warning_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"is_shop_configured" => [
"0" => 0,
"1" => "",
],
],
],
"products_per_page" => [
"label" => "Products per page",
"default" => 12,
"min" => 1,
"step" => 1,
"class" => "WP_Customize_Number_Control",
"type" => "number",
"sanitize_callback" => "absint",
],
"product_grid_pagination" => [
"label" => "Paging",
"default" => "pagination",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"pagination" => "Pagination",
"loadmore" => "Load More",
"infinity" => "Infinity",
],
],
"product_grid_load_more_text" => [
"label" => "Load More button text",
"type" => "text",
"default" => "Load More",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"product_grid_pagination" => [
"0" => "loadmore",
],
],
],
"quickview_enabled" => [
"label" => "Quick view",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"product_preview_rating" => [
"label" => "Star rating",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"shop_hide_sidebar" => [
"label" => "Hide sidebar",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"product_category_bottom_description" => [
"label" => "Show category description at the bottom of the page",
"description" => "By default, the description is displayed at the top of the category page",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"grid_image_info" => [
"label" => "Product Image",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"grid_image_fit" => [
"label" => "Main image fit in product grid",
"default" => "cover",
"sanitize_callback" => "sanitize_text_field",
"type" => "image-radio",
"class" => "WP_Customize_Image_Radio_Control",
"is_option" => true,
"choices" => [
"contain" => "https://katkotna.com/wp-content/themes/kidz/img/thumb-contain.png",
"cover" => "https://katkotna.com/wp-content/themes/kidz/img/thumb-cover.png",
],
],
"grid_image_prop" => [
"label" => "Image aspect ratio in grid (height / width)",
"default" => 1,
"type" => "slider",
"sanitize_callback" => "ideapark_sanitize_float",
"class" => "WP_Customize_Range_Control",
"min" => 0.4,
"max" => 2,
"step" => 0.1,
"dependency" => [
"grid_image_fit" => [
"0" => "contain",
],
],
],
"switch_image_on_hover" => [
"label" => "Switch image on hover",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"quickview_product_zoom" => [
"label" => "Images zoom on touch or mouseover in Quick view",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"quickview_enabled" => [
"0" => "not_empty",
],
],
],
"quickview_product_zoom_mobile_hide" => [
"label" => "Hide zoom on mobile in Quick view",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"quickview_enabled" => [
"0" => "not_empty",
],
"quickview_product_zoom" => [
"0" => "not_empty",
],
],
],
"product_mobile_settings_info" => [
"label" => "Mobile Settings",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"product_small_mobile" => [
"label" => "Mobile Layout",
"default" => "default",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"default" => "1 product per row",
"compact" => "2 products per row",
"small" => "Compact",
],
],
"filter_button_text" => [
"label" => "Filter button text",
"default" => "Filter",
"type" => "text",
"sanitize_callback" => "sanitize_text_field",
],
],
],
"26" => [
"panel" => "woocommerce",
"section_id" => "woocommerce_product_page",
"title" => "Product Page",
"priority" => 2,
"controls" => [
"product_tabs" => [
"label" => "Product Tabs (Default)",
"description" => "Enable or disable tab, and then drag and drop tabs below to set up their order",
"type" => "checklist",
"default" => "description=1|additional_information=1|reviews=1",
"choices" => [
"description" => "الوصف",
"additional_information" => "معلومات إضافية",
"reviews" => "المراجعات",
],
"sortable" => true,
"class" => "WP_Customize_Checklist_Control",
"sanitize_callback" => "sanitize_text_field",
],
"description_tab_header" => [
"label" => "Custom header of the \"Description\" tab",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"product_tabs" => [
"0" => "search=description=1",
],
],
],
"additional_information_tab_header" => [
"label" => "Custom header of the \"Additional information\" tab",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"product_tabs" => [
"0" => "search=additional_information=1",
],
],
],
"product_tabs_as_sections_desktop" => [
"label" => "Product tabs as sections on desktop",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"product_tabs_as_sections" => [
"label" => "Product tabs as sections on mobile",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"product_page_ajax_add_to_cart" => [
"label" => "Ajax Add to Cart",
"description" => "This option will enable the Ajax add to cart functionality on a product page. WooCommerce doesn`t have this option built-in, so theme implementation might not be compatible with a certain plugin you`re using, so it would be best to keep it disabled.",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"product_hide_sidebar" => [
"label" => "Hide sidebar",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"product_short_sidebar" => [
"label" => "Short sidebar",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_hide_sidebar" => [
"0" => "is_empty",
],
],
],
"hide_sku" => [
"label" => "Hide SKU",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"hide_stock" => [
"label" => "Hide stock status",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"hide_categories" => [
"label" => "Hide categories",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"hide_tags" => [
"label" => "Hide tags",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"shop_product_navigation_same_term" => [
"label" => "Product navigation in same category",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"product_share" => [
"label" => "Show share buttons",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"product_share_buttons" => [
"label" => "Share buttons",
"description" => "Enable or disable buttons, and then drag and drop buttons below to set up their order",
"type" => "checklist",
"default" => "facebook=1|twitter=1|pinterest=1|whatsapp=1",
"choices" => [
"facebook" => "Facebook",
"twitter" => "X (Twitter)",
"pinterest" => "Pinterest",
"whatsapp" => "Whatsapp",
],
"sortable" => true,
"class" => "WP_Customize_Checklist_Control",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"product_share" => [
"0" => "not_empty",
],
],
],
"product_image_info" => [
"label" => "Product Image",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"product_image_fit" => [
"label" => "Main image fit on product page",
"default" => "contain",
"sanitize_callback" => "sanitize_text_field",
"type" => "image-radio",
"class" => "WP_Customize_Image_Radio_Control",
"is_option" => true,
"choices" => [
"contain" => "https://katkotna.com/wp-content/themes/kidz/img/thumb-contain.png",
"cover" => "https://katkotna.com/wp-content/themes/kidz/img/thumb-cover.png",
],
],
"product_image_prop" => [
"label" => "Image aspect ratio on product page (height / width)",
"default" => 1,
"type" => "slider",
"sanitize_callback" => "ideapark_sanitize_float",
"class" => "WP_Customize_Range_Control",
"min" => 0.4,
"max" => 2,
"step" => 0.1,
"dependency" => [
"product_image_fit" => [
"0" => "contain",
],
],
],
"shop_product_zoom" => [
"label" => "Images zoom on touch or mouseover",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"shop_product_zoom_mobile_hide" => [
"label" => "Hide zoom on mobile",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"shop_product_zoom" => [
"0" => "not_empty",
],
],
],
"shop_product_modal" => [
"label" => "Images modal gallery",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"product_thumbnails" => [
"label" => "Product thumbnails",
"description" => "If you need thumbnails in the mobile version select the second one",
"default" => "left",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"left" => "Left of the main image",
"below" => "Below the main image",
"hide" => "Hide",
],
],
"product_thumbnails_show_mobile" => [
"label" => "Show thumbnails in the mobile version",
"description" => "Only with `Below the main image` layout.",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_thumbnails" => [
"0" => "below",
],
],
],
"video_first" => [
"label" => "Show the video thumbnail first",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
],
],
"27" => [
"panel" => "woocommerce",
"section_id" => "woocommerce_brands",
"title" => "Brands",
"priority" => 4,
"controls" => [
"product_brand_attribute" => [
"label" => "Brand attribute",
"type" => "select",
"sanitize_callback" => "sanitize_text_field",
"choices" => "ideapark_get_all_attributes",
"is_option" => true,
],
"show_product_grid_brand" => [
"label" => "Show Brand in grid",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_brand_attribute" => [
"0" => "not_empty",
],
],
],
"show_product_page_brand" => [
"label" => "Show Brand on product page",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_brand_attribute" => [
"0" => "not_empty",
],
],
],
"show_cart_page_brand" => [
"label" => "Show Brand on cart page",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"product_brand_attribute" => [
"0" => "not_empty",
],
],
],
"brands_page" => [
"label" => "Brands page",
"description" => "Page with a list of brands. Used in breadcrumbs. Add shortcode [ip-brands] to this page to display the list of brands.",
"default" => 0,
"class" => "WP_Customize_Page_Control",
"sanitize_callback" => "absint",
"dependency" => [
"product_brand_attribute" => [
"0" => "not_empty",
],
],
],
],
],
"28" => [
"panel" => "woocommerce",
"section_id" => "woocommerce_badges",
"title" => "Badges",
"priority" => 4,
"controls" => [
"outofstock_badge_info" => [
"label" => "Out of stock",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"outofstock_badge_color" => [
"label" => "Out of stock badge color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"refresh" => false,
"refresh_css" => true,
],
"outofstock_badge_text" => [
"label" => "Out of stock text",
"description" => "Disabled if empty",
"type" => "text",
"default" => "Out of stock",
"sanitize_callback" => "sanitize_text_field",
],
"featured_badge_info" => [
"label" => "Featured",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"featured_badge_color" => [
"label" => "Featured badge color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"refresh" => false,
"refresh_css" => true,
],
"featured_badge_text" => [
"label" => "Featured badge text",
"description" => "Disabled if empty",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"featured_badge_text_hide" => [
"label" => "Hide featured badges in the featured tab on the front page",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"featured_badge_text" => [
"0" => "not_empty",
],
],
],
"sale_badge_info" => [
"label" => "Sale",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"sale_badge_color_custom" => [
"label" => "Sale badge color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"refresh" => false,
"refresh_css" => true,
],
"sale_badge_text" => [
"label" => "Sale badge text",
"description" => "Disabled if empty",
"type" => "text",
"default" => "Sale!",
"sanitize_callback" => "sanitize_text_field",
],
"sale_badge_layout" => [
"label" => "Show",
"default" => "percentage",
"type" => "radio",
"choices" => [
"percentage" => "Percentage",
"text" => "Text",
],
"sanitize_callback" => "sanitize_text_field",
],
"new_badge_info" => [
"label" => "New",
"class" => "WP_Customize_Info_Control",
"sanitize_callback" => "sanitize_text_field",
],
"new_badge_color_custom" => [
"label" => "New badge color",
"class" => "WP_Customize_Color_Control",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"refresh" => false,
"refresh_css" => true,
],
"new_badge_text" => [
"label" => "New badge text",
"description" => "Disabled if empty",
"type" => "text",
"default" => "New",
"sanitize_callback" => "sanitize_text_field",
],
"product_newness" => [
"label" => "Product newness",
"description" => "Display the New badge for how many days? Set 0 for disable `NEW` badge.",
"default" => 5,
"step" => 1,
"min" => 0,
"class" => "WP_Customize_Number_Control",
"type" => "number",
"sanitize_callback" => "absint",
],
],
],
"29" => [
"panel" => "woocommerce",
"section_id" => "woocommerce_wishlist",
"title" => "Wishlist",
"priority" => 4,
"controls" => [
"wishlist_page" => [
"label" => "Wishlist page",
"description" => "Deselect to disable wishlist",
"default" => 0,
"class" => "WP_Customize_Page_Control",
"sanitize_callback" => "absint",
],
"wishlist_share" => [
"label" => "Wishlist share buttons",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"wishlist_page" => [
"0" => "not_empty",
],
],
],
],
],
"30" => [
"panel" => "woocommerce",
"section_id" => "woocommerce_related",
"title" => "Related products, Up-Sells, Cross-Sells",
"priority" => 4,
"controls" => [
"related_product_number" => [
"label" => "Number of related products",
"default" => 4,
"min" => 0,
"step" => 1,
"class" => "WP_Customize_Number_Control",
"type" => "number",
"sanitize_callback" => "absint",
],
"related_product_header" => [
"label" => "Related products custom header",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"upsells_product_header" => [
"label" => "Up-Sells custom header",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
"cross_sells_product_header" => [
"label" => "Cross-Sells custom header",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
],
],
],
"31" => [
"panel" => "woocommerce",
"section_id" => "woocommerce_recently",
"title" => "Recently viewed products",
"priority" => 4,
"controls" => [
"recently_enabled" => [
"label" => "Enable recently viewed products",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"recently_product_number" => [
"label" => "Number of products",
"default" => 4,
"min" => 0,
"step" => 1,
"class" => "WP_Customize_Number_Control",
"type" => "number",
"sanitize_callback" => "absint",
"dependency" => [
"recently_enabled" => [
"0" => "not_empty",
],
],
],
"recently_product_show" => [
"label" => "Show on Product page",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"recently_enabled" => [
"0" => "not_empty",
],
],
],
"recently_shop_show" => [
"label" => "Show on Shop page",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"recently_enabled" => [
"0" => "not_empty",
],
],
],
"recently_cart_show" => [
"label" => "Show on Cart page",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"recently_enabled" => [
"0" => "not_empty",
],
],
],
"recently_product_header" => [
"label" => "Custom header",
"type" => "text",
"default" => "",
"sanitize_callback" => "sanitize_text_field",
"dependency" => [
"recently_enabled" => [
"0" => "not_empty",
],
],
],
"recently_position" => [
"label" => "Position",
"default" => "above",
"sanitize_callback" => "sanitize_text_field",
"type" => "select",
"choices" => [
"above" => "Above other sections",
"below" => "Below other sections",
],
"dependency" => [
"recently_enabled" => [
"0" => "not_empty",
],
],
],
],
],
"32" => [
"panel" => "woocommerce",
"section_id" => "woocommerce_cart",
"title" => "Cart",
"priority" => 10,
"controls" => [
"popup_cart_layout" => [
"label" => "Pop-up Cart layout (Desktop)",
"default" => "default",
"sanitize_callback" => "sanitize_text_field",
"type" => "radio",
"choices" => [
"default" => "Default",
"sidebar" => "Sidebar",
"disable" => "Disable",
],
],
"popup_cart_auto_open_desktop" => [
"label" => "Open the pop-up cart after adding the product (Desktop)",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"popup_cart_layout" => [
"0" => "sidebar",
],
],
],
"popup_cart_auto_open_mobile" => [
"label" => "Open the pop-up cart after adding the product (Mobile)",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"dependency" => [
"popup_cart_layout" => [
"0" => "sidebar",
],
],
],
"popup_cart_modal" => [
"label" => "Clicking outside the sidebar closes the cart",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"cart_auto_update" => [
"label" => "Auto update cart when quantity changed on the cart page",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"expand_coupon" => [
"label" => "Expand Coupon Code block",
"default" => false,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
],
],
"33" => [
"panel" => "woocommerce",
"section" => "woocommerce_checkout",
"priority" => 1,
"controls" => [
"product_two_columns_checkout" => [
"label" => "Display form fields on the Checkout page in two columns",
"default" => true,
"type" => "checkbox",
"sanitize_callback" => "ideapark_sanitize_checkbox",
],
"expand_coupon_info" => [
"html" => "<a href=\"#\" class=\"ideapark-control-focus\" data-control=\"expand_coupon\">Expand Coupon Code block</a>",
"class" => "WP_Customize_HTML_Control",
"sanitize_callback" => "sanitize_text_field",
"priority" => 100,
],
"last_option" => [
"label" => "",
"description" => "",
"type" => "hidden",
"default" => "",
"sanitize_callback" => "ideapark_sanitize_checkbox",
"class" => "WP_Customize_Hidden_Control",
],
],
],
];

global $ideapark_customize_mods_def;
$ideapark_customize_mods_def = [
"logo_zoom" => 1,
"logo_zoom_mobile" => 1,
"hide_inner_background" => true,
"home_boxed" => "fullscreen",
"search_type" => "search-type-2",
"ajax_search_limit" => 8,
"search_products_only" => true,
"search_by_sku" => false,
"search_by_category" => false,
"search_by_tag" => false,
"arrows_type" => "normal",
"disable_block_editor" => true,
"sticky_sidebar" => true,
"to_top_button" => false,
"to_top_button_color" => "",
"header_type" => "header-type-1",
"icon_auth" => false,
"icon_search" => true,
"icon_cart" => true,
"wishlist_enabled" => true,
"mega_menu" => true,
"main_menu_view" => "main-menu-icons",
"main_menu_width" => 105,
"main_menu_font_size" => 12,
"main_menu_responsive" => false,
"top_menu" => true,
"top_menu_color" => "",
"top_menu_background_color" => "",
"top_menu_text" => "",
"top_menu_text_phone_clickable" => false,
"top_menu_auth" => true,
"sticky_menu" => true,
"sticky_type" => "sticky-type-1",
"footer_layout" => "default",
"footer_contacts" => "",
"footer_copyright" => "&copy; Copyright 2022, Kidz WordPress Theme",
"footer_text_color" => "",
"footer_background_color" => "",
"soc_background_color" => "#404E65",
"soc_color" => "#FFFFFF",
"facebook" => "",
"instagram" => "",
"vk" => "",
"ok" => "",
"telegram" => "",
"whatsapp" => "",
"twitter" => "",
"youtube" => "",
"front_page_builder_enabled" => true,
"home_sections" => "slider=1|banner-4=1|product-tabs=1|brands=1|big-banner=0|posts=1|reviews=1|text=1|subscribe=0|html=0|shortcode=0",
"home_fullwidth_slider" => true,
"slider_shortcode" => "",
"slider_effect" => "slide",
"slider_items" => 5,
"slider_interval" => 5000,
"slider_hide_arrows" => false,
"slider_hide_dots" => false,
"home_banners_4_order" => "fixed",
"home_big_banner_header" => "",
"home_big_banner_subheader" => "",
"home_big_banner_button_text" => "",
"home_big_banner_text_align" => "text-center",
"home_big_banner_link" => "",
"home_big_banner_image_position_x" => "center",
"home_big_banner_image_position_y" => "center",
"home_big_banner_image_size" => "auto",
"home_big_banner_parallax" => true,
"home_big_banner_text_color" => "#404E65",
"home_big_banner_button_color" => "#404E65",
"home_big_banner_background_color" => "",
"home_big_banner_container" => true,
"home_tab_products" => 12,
"home_tab_orderby" => "",
"home_tab_order" => "ASC",
"home_tab_carousel" => false,
"home_tab_view_more" => false,
"home_tab_view_more_item" => false,
"home_product_order" => "featured_products=1|sale_products=1|best_selling_products=1|recent_products=1",
"home_tab_shortcode" => "",
"home_tab_shortcode_title" => "Products",
"home_featured_title" => "Featured",
"home_sale_title" => "On a Sale",
"home_best_selling_title" => "Bestsellers",
"home_recent_title" => "Latest",
"home_tab_background_color" => "",
"home_tab_padding_top" => true,
"home_tab_padding_bottom" => true,
"home_brands_interval" => 0,
"home_brands_background_color" => "#F4F8FF",
"home_brands_mobile_dots" => true,
"home_post_title" => "Blog Posts",
"home_post_category" => 0,
"home_post_background_color" => "",
"home_post_count" => 4,
"home_review_interval" => 0,
"home_review_background_color" => "",
"home_review_mobile_dots" => true,
"home_text_background_color" => "",
"home_text_hide_header" => false,
"home_html_header" => "",
"home_html_content_type" => "WYSIWYG",
"home_html_content" => "",
"home_html_content_source" => "",
"home_html_background_color" => "",
"home_html_container" => true,
"home_html_margins" => true,
"home_shortcode_header" => "",
"home_shortcode_content" => "",
"home_shortcode_background_color" => "",
"home_shortcode_container" => true,
"home_shortcode_margins" => true,
"home_subscribe_header" => "Subscribe to Newsletter",
"home_subscribe_content" => "",
"home_subscribe_background_color" => "#EFF7FF",
"home_subscribe_container" => true,
"home_subscribe_margins" => false,
"theme_font_0" => "Open Sans",
"theme_font_1" => "Fredoka",
"theme_font_1_weight" => "600",
"theme_font_2" => "Montserrat",
"theme_font_subsets" => "latin-ext",
"post_hide_featured_image" => false,
"post_hide_category" => false,
"post_hide_date" => false,
"post_hide_share" => false,
"post_hide_tags" => false,
"post_hide_comment" => false,
"post_hide_author" => true,
"post_hide_postnav" => false,
"post_hide_related" => false,
"sidebar_blog" => true,
"sidebar_post" => true,
"sidebar_page" => true,
"contact_phones" => "1-800-312-2121",
"contact_email" => "<a href=\"mailto:example@domain.net\">example@domain.net</a>",
"contact_address" => "555 California str, Suite 100<br>San Francisco, CA 94107",
"contact_form_shortcode" => "",
"contact_map_shortcode" => "",
"use_minified_css" => true,
"use_minified_js" => true,
"load_jquery_in_footer" => true,
"lazyload" => true,
"google_fonts_display_swap" => false,
"js_delay" => true,
"accent_color_custom" => "#56B0F2",
"accent_color_2_custom" => "#FF5B4B",
"base_color_custom" => "#404E65",
"star_color_custom" => "",
"store_notice" => "top",
"store_notice_button_hide" => false,
"store_notice_button_text" => "",
"store_notice_color" => "",
"store_notice_background_color" => "",
"disable_purchase" => false,
"hide_prices" => false,
"hide_uncategorized" => true,
"hidden_product_category" => 0,
"hide_variable_price_range" => false,
"product_breadcrumbs_home" => false,
"product_thumbnail_cart_mobile" => true,
"is_shop_configured" => "ideapark_is_shop_configured",
"products_per_page" => 12,
"product_grid_pagination" => "pagination",
"product_grid_load_more_text" => "Load More",
"quickview_enabled" => true,
"product_preview_rating" => false,
"shop_hide_sidebar" => false,
"product_category_bottom_description" => false,
"grid_image_fit" => "cover",
"grid_image_prop" => 1,
"switch_image_on_hover" => false,
"quickview_product_zoom" => false,
"quickview_product_zoom_mobile_hide" => false,
"product_small_mobile" => "default",
"filter_button_text" => "Filter",
"product_tabs" => "description=1|additional_information=1|reviews=1",
"description_tab_header" => "",
"additional_information_tab_header" => "",
"product_tabs_as_sections_desktop" => false,
"product_tabs_as_sections" => false,
"product_page_ajax_add_to_cart" => false,
"product_hide_sidebar" => true,
"product_short_sidebar" => true,
"hide_sku" => false,
"hide_stock" => false,
"hide_categories" => false,
"hide_tags" => false,
"shop_product_navigation_same_term" => true,
"product_share" => true,
"product_share_buttons" => "facebook=1|twitter=1|pinterest=1|whatsapp=1",
"product_image_fit" => "contain",
"product_image_prop" => 1,
"shop_product_zoom" => false,
"shop_product_zoom_mobile_hide" => false,
"shop_product_modal" => true,
"product_thumbnails" => "left",
"product_thumbnails_show_mobile" => true,
"video_first" => false,
"show_product_grid_brand" => false,
"show_product_page_brand" => false,
"show_cart_page_brand" => false,
"brands_page" => 0,
"outofstock_badge_color" => "",
"outofstock_badge_text" => "Out of stock",
"featured_badge_color" => "",
"featured_badge_text" => "",
"featured_badge_text_hide" => false,
"sale_badge_color_custom" => "",
"sale_badge_text" => "Sale!",
"sale_badge_layout" => "percentage",
"new_badge_color_custom" => "",
"new_badge_text" => "New",
"product_newness" => 5,
"wishlist_page" => 0,
"wishlist_share" => true,
"related_product_number" => 4,
"related_product_header" => "",
"upsells_product_header" => "",
"cross_sells_product_header" => "",
"recently_enabled" => false,
"recently_product_number" => 4,
"recently_product_show" => false,
"recently_shop_show" => false,
"recently_cart_show" => false,
"recently_product_header" => "",
"recently_position" => "above",
"popup_cart_layout" => "default",
"popup_cart_auto_open_desktop" => false,
"popup_cart_auto_open_mobile" => false,
"popup_cart_modal" => false,
"cart_auto_update" => false,
"expand_coupon" => false,
"product_two_columns_checkout" => true,
"last_option" => "",
];

global $ideapark_customize_mods_names;
$ideapark_customize_mods_names = [
"0" => "logo",
"1" => "logo_zoom",
"2" => "logo_zoom_mobile",
"3" => "hide_inner_background",
"4" => "home_boxed",
"5" => "search_type",
"6" => "ajax_search_limit",
"7" => "search_products_only",
"8" => "search_by_sku",
"9" => "search_by_category",
"10" => "search_by_tag",
"11" => "search_by_brand_info",
"12" => "arrows_type",
"13" => "disable_block_editor",
"14" => "sticky_sidebar",
"15" => "to_top_button",
"16" => "to_top_button_color",
"17" => "header_settings_info",
"18" => "header_type",
"19" => "icon_auth",
"20" => "icon_search",
"21" => "icon_cart",
"22" => "wishlist_enabled",
"23" => "wishlist_is_disabled",
"24" => "menu_settings_info",
"25" => "mega_menu",
"26" => "main_menu_view",
"27" => "main_menu_width",
"28" => "main_menu_font_size",
"29" => "main_menu_responsive",
"30" => "top_menu_settings_info",
"31" => "top_menu",
"32" => "top_menu_color",
"33" => "top_menu_background_color",
"34" => "top_menu_text",
"35" => "top_menu_text_phone_clickable",
"36" => "top_menu_auth",
"37" => "sticky_menu_settings_info",
"38" => "sticky_menu",
"39" => "sticky_type",
"40" => "footer_layout",
"41" => "logo_footer",
"42" => "footer_contacts",
"43" => "footer_copyright",
"44" => "footer_text_color",
"45" => "footer_background_color",
"46" => "soc_background_color",
"47" => "soc_color",
"48" => "facebook",
"49" => "instagram",
"50" => "vk",
"51" => "ok",
"52" => "telegram",
"53" => "whatsapp",
"54" => "twitter",
"55" => "youtube",
"56" => "vimeo",
"57" => "snapchat",
"58" => "tiktok",
"59" => "linkedin",
"60" => "flickr",
"61" => "pinterest",
"62" => "tumblr",
"63" => "dribbble",
"64" => "github",
"65" => "custom_soc_info",
"66" => "custom_soc_icon",
"67" => "custom_soc_url",
"68" => "front_page_builder_enabled",
"69" => "home_sections",
"70" => "home_slider_is_disabled",
"71" => "home_fullwidth_slider",
"72" => "slider_shortcode",
"73" => "slider_effect",
"74" => "slider_items",
"75" => "slider_interval",
"76" => "slider_hide_arrows",
"77" => "slider_hide_dots",
"78" => "home_slider_edit",
"79" => "home_banner_4_is_disabled",
"80" => "home_banners_4_order",
"81" => "home_banners_edit",
"82" => "home_banner_big_is_disabled",
"83" => "home_big_banner_header",
"84" => "home_big_banner_subheader",
"85" => "home_big_banner_button_text",
"86" => "home_big_banner_text_align",
"87" => "home_big_banner_link",
"88" => "home_big_banner_image",
"89" => "home_big_banner_image_position_x",
"90" => "home_big_banner_image_position_y",
"91" => "home_big_banner_image_size",
"92" => "home_big_banner_parallax",
"93" => "home_big_banner_text_color",
"94" => "home_big_banner_button_color",
"95" => "home_big_banner_background_color",
"96" => "home_big_banner_container",
"97" => "home_tab_products_is_disabled",
"98" => "home_tab_products",
"99" => "home_tab_orderby",
"100" => "home_tab_order",
"101" => "home_tab_carousel",
"102" => "home_tab_view_more",
"103" => "home_tab_view_more_item",
"104" => "home_product_order",
"105" => "home_tab_shortcode",
"106" => "home_tab_shortcode_manual",
"107" => "home_tab_shortcode_title",
"108" => "home_featured_title",
"109" => "home_sale_title",
"110" => "home_best_selling_title",
"111" => "home_recent_title",
"112" => "home_tab_background_color",
"113" => "home_tab_padding_top",
"114" => "home_tab_padding_bottom",
"115" => "home_brands_is_disabled",
"116" => "home_brands_interval",
"117" => "home_brands_background_color",
"118" => "home_brands_mobile_dots",
"119" => "home_brands_edit",
"120" => "home_post_is_disabled",
"121" => "home_post_title",
"122" => "home_post_category",
"123" => "home_post_background_color",
"124" => "home_post_count",
"125" => "home_reviews_is_disabled",
"126" => "home_review_interval",
"127" => "home_review_background_color",
"128" => "home_review_mobile_dots",
"129" => "home_review_edit",
"130" => "home_text_is_disabled",
"131" => "home_text_background_color",
"132" => "home_text_hide_header",
"133" => "home_html_is_disabled",
"134" => "home_html_header",
"135" => "home_html_content_type",
"136" => "home_html_content",
"137" => "home_html_content_source",
"138" => "home_html_background_color",
"139" => "home_html_container",
"140" => "home_html_margins",
"141" => "home_shortcode_is_disabled",
"142" => "home_shortcode_header",
"143" => "home_shortcode_content",
"144" => "home_shortcode_background_color",
"145" => "home_shortcode_container",
"146" => "home_shortcode_margins",
"147" => "home_subscribe_is_disabled",
"148" => "home_subscribe_header",
"149" => "home_subscribe_content",
"150" => "home_subscribe_background_color",
"151" => "home_subscribe_container",
"152" => "home_subscribe_margins",
"153" => "theme_font_0",
"154" => "theme_font_1",
"155" => "theme_font_1_weight",
"156" => "theme_font_2",
"157" => "theme_font_subsets",
"158" => "post_hide_featured_image",
"159" => "post_hide_category",
"160" => "post_hide_date",
"161" => "post_hide_share",
"162" => "post_hide_tags",
"163" => "post_hide_comment",
"164" => "post_hide_author",
"165" => "post_hide_postnav",
"166" => "post_hide_related",
"167" => "sidebar_info",
"168" => "sidebar_blog",
"169" => "sidebar_post",
"170" => "sidebar_page",
"171" => "contact_phones",
"172" => "contact_email",
"173" => "contact_address",
"174" => "contact_form_shortcode",
"175" => "contact_map_shortcode",
"176" => "use_minified_css",
"177" => "use_minified_js",
"178" => "load_jquery_in_footer",
"179" => "lazyload",
"180" => "google_fonts_display_swap",
"181" => "js_delay",
"182" => "accent_color_custom",
"183" => "accent_color_2_custom",
"184" => "base_color_custom",
"185" => "star_color_custom",
"186" => "store_notice",
"187" => "store_notice_button_hide",
"188" => "store_notice_button_text",
"189" => "store_notice_color",
"190" => "store_notice_background_color",
"191" => "disable_purchase",
"192" => "hide_prices",
"193" => "hide_uncategorized",
"194" => "hidden_product_category",
"195" => "hide_variable_price_range",
"196" => "product_breadcrumbs_home",
"197" => "product_thumbnail_cart_mobile",
"198" => "is_shop_configured",
"199" => "shop_is_not_configured",
"200" => "products_per_page",
"201" => "product_grid_pagination",
"202" => "product_grid_load_more_text",
"203" => "quickview_enabled",
"204" => "product_preview_rating",
"205" => "shop_hide_sidebar",
"206" => "product_category_bottom_description",
"207" => "grid_image_info",
"208" => "grid_image_fit",
"209" => "grid_image_prop",
"210" => "switch_image_on_hover",
"211" => "quickview_product_zoom",
"212" => "quickview_product_zoom_mobile_hide",
"213" => "product_mobile_settings_info",
"214" => "product_small_mobile",
"215" => "filter_button_text",
"216" => "product_tabs",
"217" => "description_tab_header",
"218" => "additional_information_tab_header",
"219" => "product_tabs_as_sections_desktop",
"220" => "product_tabs_as_sections",
"221" => "product_page_ajax_add_to_cart",
"222" => "product_hide_sidebar",
"223" => "product_short_sidebar",
"224" => "hide_sku",
"225" => "hide_stock",
"226" => "hide_categories",
"227" => "hide_tags",
"228" => "shop_product_navigation_same_term",
"229" => "product_share",
"230" => "product_share_buttons",
"231" => "product_image_info",
"232" => "product_image_fit",
"233" => "product_image_prop",
"234" => "shop_product_zoom",
"235" => "shop_product_zoom_mobile_hide",
"236" => "shop_product_modal",
"237" => "product_thumbnails",
"238" => "product_thumbnails_show_mobile",
"239" => "video_first",
"240" => "product_brand_attribute",
"241" => "show_product_grid_brand",
"242" => "show_product_page_brand",
"243" => "show_cart_page_brand",
"244" => "brands_page",
"245" => "outofstock_badge_info",
"246" => "outofstock_badge_color",
"247" => "outofstock_badge_text",
"248" => "featured_badge_info",
"249" => "featured_badge_color",
"250" => "featured_badge_text",
"251" => "featured_badge_text_hide",
"252" => "sale_badge_info",
"253" => "sale_badge_color_custom",
"254" => "sale_badge_text",
"255" => "sale_badge_layout",
"256" => "new_badge_info",
"257" => "new_badge_color_custom",
"258" => "new_badge_text",
"259" => "product_newness",
"260" => "wishlist_page",
"261" => "wishlist_share",
"262" => "related_product_number",
"263" => "related_product_header",
"264" => "upsells_product_header",
"265" => "cross_sells_product_header",
"266" => "recently_enabled",
"267" => "recently_product_number",
"268" => "recently_product_show",
"269" => "recently_shop_show",
"270" => "recently_cart_show",
"271" => "recently_product_header",
"272" => "recently_position",
"273" => "popup_cart_layout",
"274" => "popup_cart_auto_open_desktop",
"275" => "popup_cart_auto_open_mobile",
"276" => "popup_cart_modal",
"277" => "cart_auto_update",
"278" => "expand_coupon",
"279" => "product_two_columns_checkout",
"280" => "expand_coupon_info",
"281" => "last_option",
];

global $ideapark_customize_mods_images;
$ideapark_customize_mods_images = [
"0" => "logo",
"1" => "logo_footer",
"2" => "custom_soc_icon",
"3" => "home_big_banner_image",
];

